// Code generated by protoc-gen-go. DO NOT EDIT.
// source: product.proto

/*
Package product is a generated protocol buffer package.

It is generated from these files:
	product.proto

It has these top-level messages:
	ProductQueryRequest
	ProductResponse
	ProductListResponse
*/
package product

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ProductQueryRequest struct {
	ID         int32 `protobuf:"varint,1,opt,name=ID" json:"ID,omitempty"`
	CategoryID int32 `protobuf:"varint,2,opt,name=CategoryID" json:"CategoryID,omitempty"`
}

func (m *ProductQueryRequest) Reset()                    { *m = ProductQueryRequest{} }
func (m *ProductQueryRequest) String() string            { return proto.CompactTextString(m) }
func (*ProductQueryRequest) ProtoMessage()               {}
func (*ProductQueryRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ProductQueryRequest) GetID() int32 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *ProductQueryRequest) GetCategoryID() int32 {
	if m != nil {
		return m.CategoryID
	}
	return 0
}

type ProductResponse struct {
	ID          int32   `protobuf:"varint,1,opt,name=ID" json:"ID,omitempty"`
	CategoryID  int32   `protobuf:"varint,2,opt,name=CategoryID" json:"CategoryID,omitempty"`
	Name        string  `protobuf:"bytes,3,opt,name=Name" json:"Name,omitempty"`
	Description string  `protobuf:"bytes,4,opt,name=Description" json:"Description,omitempty"`
	Image       string  `protobuf:"bytes,5,opt,name=Image" json:"Image,omitempty"`
	Stock       int32   `protobuf:"varint,6,opt,name=Stock" json:"Stock,omitempty"`
	Price       float64 `protobuf:"fixed64,7,opt,name=Price" json:"Price,omitempty"`
}

func (m *ProductResponse) Reset()                    { *m = ProductResponse{} }
func (m *ProductResponse) String() string            { return proto.CompactTextString(m) }
func (*ProductResponse) ProtoMessage()               {}
func (*ProductResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ProductResponse) GetID() int32 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *ProductResponse) GetCategoryID() int32 {
	if m != nil {
		return m.CategoryID
	}
	return 0
}

func (m *ProductResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ProductResponse) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *ProductResponse) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

func (m *ProductResponse) GetStock() int32 {
	if m != nil {
		return m.Stock
	}
	return 0
}

func (m *ProductResponse) GetPrice() float64 {
	if m != nil {
		return m.Price
	}
	return 0
}

type ProductListResponse struct {
	ProductList []*ProductResponse `protobuf:"bytes,1,rep,name=ProductList" json:"ProductList,omitempty"`
}

func (m *ProductListResponse) Reset()                    { *m = ProductListResponse{} }
func (m *ProductListResponse) String() string            { return proto.CompactTextString(m) }
func (*ProductListResponse) ProtoMessage()               {}
func (*ProductListResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ProductListResponse) GetProductList() []*ProductResponse {
	if m != nil {
		return m.ProductList
	}
	return nil
}

func init() {
	proto.RegisterType((*ProductQueryRequest)(nil), "product.ProductQueryRequest")
	proto.RegisterType((*ProductResponse)(nil), "product.ProductResponse")
	proto.RegisterType((*ProductListResponse)(nil), "product.ProductListResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for ProductService service

type ProductServiceClient interface {
	FindByID(ctx context.Context, in *ProductQueryRequest, opts ...grpc.CallOption) (*ProductResponse, error)
	FindByCategory(ctx context.Context, in *ProductQueryRequest, opts ...grpc.CallOption) (ProductService_FindByCategoryClient, error)
	FindAll(ctx context.Context, in *ProductQueryRequest, opts ...grpc.CallOption) (ProductService_FindAllClient, error)
}

type productServiceClient struct {
	cc *grpc.ClientConn
}

func NewProductServiceClient(cc *grpc.ClientConn) ProductServiceClient {
	return &productServiceClient{cc}
}

func (c *productServiceClient) FindByID(ctx context.Context, in *ProductQueryRequest, opts ...grpc.CallOption) (*ProductResponse, error) {
	out := new(ProductResponse)
	err := grpc.Invoke(ctx, "/product.ProductService/FindByID", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) FindByCategory(ctx context.Context, in *ProductQueryRequest, opts ...grpc.CallOption) (ProductService_FindByCategoryClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_ProductService_serviceDesc.Streams[0], c.cc, "/product.ProductService/FindByCategory", opts...)
	if err != nil {
		return nil, err
	}
	x := &productServiceFindByCategoryClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type ProductService_FindByCategoryClient interface {
	Recv() (*ProductResponse, error)
	grpc.ClientStream
}

type productServiceFindByCategoryClient struct {
	grpc.ClientStream
}

func (x *productServiceFindByCategoryClient) Recv() (*ProductResponse, error) {
	m := new(ProductResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *productServiceClient) FindAll(ctx context.Context, in *ProductQueryRequest, opts ...grpc.CallOption) (ProductService_FindAllClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_ProductService_serviceDesc.Streams[1], c.cc, "/product.ProductService/FindAll", opts...)
	if err != nil {
		return nil, err
	}
	x := &productServiceFindAllClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type ProductService_FindAllClient interface {
	Recv() (*ProductResponse, error)
	grpc.ClientStream
}

type productServiceFindAllClient struct {
	grpc.ClientStream
}

func (x *productServiceFindAllClient) Recv() (*ProductResponse, error) {
	m := new(ProductResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for ProductService service

type ProductServiceServer interface {
	FindByID(context.Context, *ProductQueryRequest) (*ProductResponse, error)
	FindByCategory(*ProductQueryRequest, ProductService_FindByCategoryServer) error
	FindAll(*ProductQueryRequest, ProductService_FindAllServer) error
}

func RegisterProductServiceServer(s *grpc.Server, srv ProductServiceServer) {
	s.RegisterService(&_ProductService_serviceDesc, srv)
}

func _ProductService_FindByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProductQueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).FindByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/product.ProductService/FindByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).FindByID(ctx, req.(*ProductQueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_FindByCategory_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ProductQueryRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ProductServiceServer).FindByCategory(m, &productServiceFindByCategoryServer{stream})
}

type ProductService_FindByCategoryServer interface {
	Send(*ProductResponse) error
	grpc.ServerStream
}

type productServiceFindByCategoryServer struct {
	grpc.ServerStream
}

func (x *productServiceFindByCategoryServer) Send(m *ProductResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _ProductService_FindAll_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ProductQueryRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ProductServiceServer).FindAll(m, &productServiceFindAllServer{stream})
}

type ProductService_FindAllServer interface {
	Send(*ProductResponse) error
	grpc.ServerStream
}

type productServiceFindAllServer struct {
	grpc.ServerStream
}

func (x *productServiceFindAllServer) Send(m *ProductResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _ProductService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "product.ProductService",
	HandlerType: (*ProductServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FindByID",
			Handler:    _ProductService_FindByID_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "FindByCategory",
			Handler:       _ProductService_FindByCategory_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "FindAll",
			Handler:       _ProductService_FindAll_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "product.proto",
}

func init() { proto.RegisterFile("product.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 288 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x92, 0xc1, 0x4a, 0xfb, 0x40,
	0x10, 0xc6, 0xd9, 0xb4, 0x69, 0xfe, 0xff, 0x09, 0x46, 0x18, 0x3d, 0x2c, 0x22, 0x12, 0x72, 0xca,
	0xa9, 0x48, 0xbd, 0x79, 0xb3, 0x8d, 0x42, 0x44, 0xa4, 0xdd, 0x3e, 0x41, 0x4c, 0x87, 0xb2, 0xd8,
	0x66, 0xe3, 0x66, 0x23, 0xf4, 0xd1, 0x7c, 0x20, 0xdf, 0x43, 0xb2, 0x49, 0x35, 0x14, 0x3c, 0xd8,
	0xdb, 0x7c, 0xdf, 0x2c, 0xbf, 0xd9, 0xf9, 0x18, 0x38, 0x29, 0xb5, 0x5a, 0xd5, 0xb9, 0x19, 0x97,
	0x5a, 0x19, 0x85, 0x5e, 0x27, 0xa3, 0x7b, 0x38, 0x9b, 0xb7, 0xe5, 0xa2, 0x26, 0xbd, 0x13, 0xf4,
	0x56, 0x53, 0x65, 0x30, 0x00, 0x27, 0x4d, 0x38, 0x0b, 0x59, 0xec, 0x0a, 0x27, 0x4d, 0xf0, 0x0a,
	0x60, 0x96, 0x19, 0x5a, 0x2b, 0xbd, 0x4b, 0x13, 0xee, 0x58, 0xbf, 0xe7, 0x44, 0x1f, 0x0c, 0x4e,
	0x3b, 0x8e, 0xa0, 0xaa, 0x54, 0x45, 0x45, 0x7f, 0x65, 0x20, 0xc2, 0xf0, 0x39, 0xdb, 0x12, 0x1f,
	0x84, 0x2c, 0xfe, 0x2f, 0x6c, 0x8d, 0x21, 0xf8, 0x09, 0x55, 0xb9, 0x96, 0xa5, 0x91, 0xaa, 0xe0,
	0x43, 0xdb, 0xea, 0x5b, 0x78, 0x0e, 0x6e, 0xba, 0xcd, 0xd6, 0xc4, 0x5d, 0xdb, 0x6b, 0x45, 0xe3,
	0x2e, 0x8d, 0xca, 0x5f, 0xf9, 0xc8, 0x8e, 0x69, 0x45, 0xe3, 0xce, 0xb5, 0xcc, 0x89, 0x7b, 0x21,
	0x8b, 0x99, 0x68, 0x45, 0xb4, 0xf8, 0x8e, 0xe0, 0x49, 0x56, 0x3f, 0xdf, 0xbf, 0x05, 0xbf, 0x67,
	0x73, 0x16, 0x0e, 0x62, 0x7f, 0xc2, 0xc7, 0xfb, 0x1c, 0x0f, 0xb6, 0x15, 0xfd, 0xc7, 0x93, 0x4f,
	0x06, 0x41, 0xa7, 0x97, 0xa4, 0xdf, 0x65, 0x4e, 0x38, 0x85, 0x7f, 0x0f, 0xb2, 0x58, 0x4d, 0x9b,
	0x4d, 0x2f, 0x0f, 0x29, 0xfd, 0xec, 0x2f, 0x7e, 0x9d, 0x81, 0x8f, 0x10, 0xb4, 0x8c, 0x7d, 0x6a,
	0xc7, 0x92, 0xae, 0x19, 0xce, 0xc0, 0x6b, 0x58, 0x77, 0x9b, 0xcd, 0xf1, 0x90, 0x97, 0x91, 0xbd,
	0xa6, 0x9b, 0xaf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xd8, 0xd8, 0xdb, 0x2d, 0x5e, 0x02, 0x00, 0x00,
}
