// Code generated by mockery v1.0.0
package mocks

import mock "github.com/stretchr/testify/mock"
import query "github.com/wuriyanto48/ecommerce-grpc-microservice/auth/query"

// IdentityQuery is an autogenerated mock type for the IdentityQuery type
type IdentityQuery struct {
	mock.Mock
}

// FindByEmail provides a mock function with given fields: email
func (_m *IdentityQuery) FindByEmail(email string) <-chan query.QueryResult {
	ret := _m.Called(email)

	var r0 <-chan query.QueryResult
	if rf, ok := ret.Get(0).(func(string) <-chan query.QueryResult); ok {
		r0 = rf(email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan query.QueryResult)
		}
	}

	return r0
}
