// Code generated by mockery v1.0.0
package mocks

import mock "github.com/stretchr/testify/mock"
import usecase "github.com/wuriyanto48/ecommerce-grpc-microservice/auth/usecase"

// AuthUseCase is an autogenerated mock type for the AuthUseCase type
type AuthUseCase struct {
	mock.Mock
}

// GetAccessToken provides a mock function with given fields: email, password
func (_m *AuthUseCase) GetAccessToken(email string, password string) <-chan usecase.UseCaseResult {
	ret := _m.Called(email, password)

	var r0 <-chan usecase.UseCaseResult
	if rf, ok := ret.Get(0).(func(string, string) <-chan usecase.UseCaseResult); ok {
		r0 = rf(email, password)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan usecase.UseCaseResult)
		}
	}

	return r0
}
